service: open-chair

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: GET
          integration: lambda
      - http:
          path: webhook
          method: POST
          integration: lambda